Clean & Aggregate EV Data

In [3]:
import pandas as pd

# Load raw data
ev_df = pd.read_csv("../data/Electric_Vehicle_Charging_Station_Data.csv")

# Preview
print(ev_df.shape)
print(ev_df.columns)
ev_df.head()

(148136, 17)
Index(['Station_Name', 'Address', 'City', 'State_Province', 'Zip_Postal_Code',
       'Start_Date___Time', 'Start_Time_Zone', 'End_Date___Time',
       'End_Time_Zone', 'Total_Duration__hh_mm_ss_',
       'Charging_Time__hh_mm_ss_', 'Energy__kWh_', 'GHG_Savings__kg_',
       'Gasoline_Savings__gallons_', 'Port_Type', 'ObjectID', 'ObjectId2'],
      dtype='object')

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type,ObjectID,ObjectId2
0,BOULDER / JUNCTION ST1,2280 Junction Pl,Boulder,Colorado,80301,01/01/2018 17:49,MDT,01/01/2018 19:52,MDT,02:03:02,02:02:44,6.504,2.732,0.816,Level 2,0,1
1,BOULDER / JUNCTION ST1,2280 Junction Pl,Boulder,Colorado,80301,01/02/2018 08:52,MDT,01/02/2018 09:16,MDT,00:24:34,00:24:19,2.481,1.042,0.311,Level 2,1,2
2,BOULDER / JUNCTION ST1,2280 Junction Pl,Boulder,Colorado,80301,01/02/2018 21:11,MDT,01/03/2018 06:23,MDT,09:12:21,03:40:52,15.046,6.319,1.888,Level 2,2,3
3,BOULDER / ALPINE ST1,1275 Alpine Ave,Boulder,Colorado,80304,01/03/2018 09:19,MDT,01/03/2018 11:14,MDT,01:54:51,01:54:29,6.947,2.918,0.872,Level 2,3,4
4,BOULDER / BASELINE ST1,900 Baseline Rd,Boulder,Colorado,80302,01/03/2018 14:13,MDT,01/03/2018 14:30,MDT,00:16:58,00:16:44,1.800,0.756,0.226,Level 2,4,5

In [4]:
# Drop ObjectID and ObjectId2 columns
ev_df.drop(columns=['ObjectID', 'ObjectId2'], inplace=True)

# Optional: check remaining columns
print(ev_df.columns)

Index(['Station_Name', 'Address', 'City', 'State_Province', 'Zip_Postal_Code',
       'Start_Date___Time', 'Start_Time_Zone', 'End_Date___Time',
       'End_Time_Zone', 'Total_Duration__hh_mm_ss_',
       'Charging_Time__hh_mm_ss_', 'Energy__kWh_', 'GHG_Savings__kg_',
       'Gasoline_Savings__gallons_', 'Port_Type'],
      dtype='object')

In [5]:
# Show exact duplicate rows (including all columns)
duplicate_rows = ev_df[ev_df.duplicated(keep=False)]

# Display them
print(duplicate_rows)

# Optional: check how many duplicates exist
print(f"\nTotal duplicate rows: {duplicate_rows.shape[0]}")

                       Station_Name           Address     City State_Province  \
0            BOULDER / JUNCTION ST1  2280 Junction Pl  Boulder       Colorado
1            BOULDER / JUNCTION ST1  2280 Junction Pl  Boulder       Colorado
2            BOULDER / JUNCTION ST1  2280 Junction Pl  Boulder       Colorado
3              BOULDER / ALPINE ST1   1275 Alpine Ave  Boulder       Colorado
4            BOULDER / BASELINE ST1   900 Baseline Rd  Boulder       Colorado
...                             ...               ...      ...            ...
138397   MUNICIPAL SC / 1100WALNUT1       1100 Walnut  Boulder       Colorado
138728    BOULDER / CARPENTER PARK2      1505 30th St  Boulder       Colorado
138729    BOULDER / CARPENTER PARK2      1505 30th St  Boulder       Colorado
147645  MUNICIPAL SC / 1104 SPRUCE1    1100 Spruce St  Boulder       Colorado
147647  MUNICIPAL SC / 1104 SPRUCE1    1100 Spruce St  Boulder       Colorado

        Zip_Postal_Code Start_Date___Time Start_Time_Zone   End_Date___Time  \
0                 80301  01/01/2018 17:49             MDT  01/01/2018 19:52
1                 80301  01/02/2018 08:52             MDT  01/02/2018 09:16
2                 80301  01/02/2018 21:11             MDT  01/03/2018 06:23
3                 80304  01/03/2018 09:19             MDT  01/03/2018 11:14
4                 80302  01/03/2018 14:13             MDT  01/03/2018 14:30
...                 ...               ...             ...               ...
138397            80302  08/08/2023 20:07             MDT  08/08/2023 21:23
138728            80303  08/12/2023 18:38             MDT  08/12/2023 18:40
138729            80303  08/12/2023 18:38             MDT  08/12/2023 18:40
147645            80302  10/30/2023 20:42             MDT  10/30/2023 20:44
147647            80302  10/30/2023 20:42             MDT  10/30/2023 20:44

       End_Time_Zone Total_Duration__hh_mm_ss_ Charging_Time__hh_mm_ss_  \
0                MDT                  02:03:02                 02:02:44
1                MDT                  00:24:34                 00:24:19
2                MDT                  09:12:21                 03:40:52
3                MDT                  01:54:51                 01:54:29
4                MDT                  00:16:58                 00:16:44
...              ...                       ...                      ...
138397           MDT                  01:16:01                 01:15:44
138728           MDT                  00:01:59                 00:00:00
138729           MDT                  00:01:59                 00:00:00
147645           MDT                  00:02:00                 00:00:00
147647           MDT                  00:02:00                 00:00:00

        Energy__kWh_  GHG_Savings__kg_  Gasoline_Savings__gallons_ Port_Type
0              6.504             2.732                       0.816   Level 2
1              2.481             1.042                       0.311   Level 2
2             15.046             6.319                       1.888   Level 2
3              6.947             2.918                       0.872   Level 2
4              1.800             0.756                       0.226   Level 2
...              ...               ...                         ...       ...
138397         7.462             5.298                       0.936   Level 2
138728         0.000             0.000                       0.000   Level 2
138729         0.000             0.000                       0.000   Level 2
147645         0.000             0.000                       0.000   Level 2
147647         0.000             0.000                       0.000   Level 2

[125226 rows x 15 columns]

Total duplicate rows: 125226

In [6]:
# Get the indices of exact duplicate rows
duplicate_indices = ev_df[ev_df.duplicated(keep=False)].index

# Display the indices
print(duplicate_indices)

# Optional: number of duplicate rows
print(f"\nTotal duplicate rows: {len(duplicate_indices)}")

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       138391, 138392, 138393, 138394, 138396, 138397, 138728, 138729, 147645,
       147647],
      dtype='int64', length=125226)

Total duplicate rows: 125226

In [7]:
# Find all exact duplicates
duplicates = ev_df[ev_df.duplicated(keep=False)]

# Group by all columns to find repeated rows and their indices
grouped_duplicates = duplicates.groupby(duplicates.columns.tolist(), as_index=False)

# Show 5 example duplicated rows with their indices
example_duplicates = []

for _, group in grouped_duplicates:
    if len(group) > 1:
        example_duplicates.append(group.index.tolist())
    if len(example_duplicates) >= 5:
        break

# Display the results
for i, dup_indexes in enumerate(example_duplicates, 1):
    print(f"Example {i}: Indices {dup_indexes}")
    display(ev_df.loc[dup_indexes])

Example 1: Indices [22622, 94530]

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
22622,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/01/2021 12:42,MDT,01/01/2021 13:44,MDT,01:01:32,01:01:21,6.172,2.592,0.775,Level 2
94530,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/01/2021 12:42,MDT,01/01/2021 13:44,MDT,01:01:32,01:01:21,6.172,2.592,0.775,Level 2

Example 2: Indices [52701, 122741]

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
52701,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/01/2023 10:55,MST,01/01/2023 13:51,MST,02:55:45,02:55:32,17.533,12.448,2.2,Level 2
122741,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/01/2023 10:55,MST,01/01/2023 13:51,MST,02:55:45,02:55:32,17.533,12.448,2.2,Level 2

Example 3: Indices [22740, 94582]

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
22740,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/02/2021 16:28,MDT,01/02/2021 17:38,MDT,01:09:45,01:09:36,6.961,2.924,0.874,Level 2
94582,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/02/2021 16:28,MDT,01/02/2021 17:38,MDT,01:09:45,01:09:36,6.961,2.924,0.874,Level 2

Example 4: Indices [33790, 103444]

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
33790,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/02/2022 15:34,MST,01/02/2022 17:04,MST,01:29:12,01:29:01,8.554,6.073,1.073,Level 2
103444,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/02/2022 15:34,MST,01/02/2022 17:04,MST,01:29:12,01:29:01,8.554,6.073,1.073,Level 2

Example 5: Indices [52684, 122786]

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
52684,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/02/2023 12:57,MST,01/02/2023 16:15,MST,03:18:48,03:18:37,17.639,12.524,2.214,Level 2
122786,BOULDER / AIRPORT ST1,3335 Airport Rd,Boulder,Colorado,80301,01/02/2023 12:57,MST,01/02/2023 16:15,MST,03:18:48,03:18:37,17.639,12.524,2.214,Level 2

In [8]:
# Keep only the first 70196 rows
ev_df1 = ev_df.iloc[:70194]

# Optional: reset index after slicing
ev_df1.reset_index(drop=True, inplace=True)

# Confirm the shape
print("New shape:", ev_df1.shape)

New shape: (70194, 15)

In [9]:
# Show the last row
ev_df1.tail(1)

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
70193,BOULDER / VALMONT ST2,5333 Valmont Rd,Boulder,Colorado,80301,31/08/2023 09:54,MDT,31/08/2023 13:48,MDT,03:53:49,03:53:34,23.604,16.759,2.962,Level 2

In [10]:
# Shape before removing duplicates
print("Before drop:", ev_df.shape)

# Drop exact duplicates
ev_df = ev_df.drop_duplicates()

# Shape after removing duplicates
print("After drop:", ev_df.shape)

Before drop: (148136, 15)
After drop: (85519, 15)

In [11]:
print(ev_df.columns)

Index(['Station_Name', 'Address', 'City', 'State_Province', 'Zip_Postal_Code',
       'Start_Date___Time', 'Start_Time_Zone', 'End_Date___Time',
       'End_Time_Zone', 'Total_Duration__hh_mm_ss_',
       'Charging_Time__hh_mm_ss_', 'Energy__kWh_', 'GHG_Savings__kg_',
       'Gasoline_Savings__gallons_', 'Port_Type'],
      dtype='object')

In [12]:
ev_df.head()

,Station_Name,Address,City,State_Province,Zip_Postal_Code,Start_Date___Time,Start_Time_Zone,End_Date___Time,End_Time_Zone,Total_Duration__hh_mm_ss_,Charging_Time__hh_mm_ss_,Energy__kWh_,GHG_Savings__kg_,Gasoline_Savings__gallons_,Port_Type
0,BOULDER / JUNCTION ST1,2280 Junction Pl,Boulder,Colorado,80301,01/01/2018 17:49,MDT,01/01/2018 19:52,MDT,02:03:02,02:02:44,6.504,2.732,0.816,Level 2
1,BOULDER / JUNCTION ST1,2280 Junction Pl,Boulder,Colorado,80301,01/02/2018 08:52,MDT,01/02/2018 09:16,MDT,00:24:34,00:24:19,2.481,1.042,0.311,Level 2
2,BOULDER / JUNCTION ST1,2280 Junction Pl,Boulder,Colorado,80301,01/02/2018 21:11,MDT,01/03/2018 06:23,MDT,09:12:21,03:40:52,15.046,6.319,1.888,Level 2
3,BOULDER / ALPINE ST1,1275 Alpine Ave,Boulder,Colorado,80304,01/03/2018 09:19,MDT,01/03/2018 11:14,MDT,01:54:51,01:54:29,6.947,2.918,0.872,Level 2
4,BOULDER / BASELINE ST1,900 Baseline Rd,Boulder,Colorado,80302,01/03/2018 14:13,MDT,01/03/2018 14:30,MDT,00:16:58,00:16:44,1.800,0.756,0.226,Level 2

In [13]:
import pandas as pd

# Ensure the column is string type
ev_df['Start_Date___Time'] = ev_df['Start_Date___Time'].astype(str)

# Find the first row containing "05/06/2023"
mask = ev_df['Start_Date___Time'].str.contains("05/06/2023")
if mask.any():
    cutoff_index = mask.idxmax()  # index of first match

    # Split the DataFrame
    df_before = ev_df.iloc[:cutoff_index].copy()
    df_after = ev_df.iloc[cutoff_index:].copy()

    # Convert date using correct formats
    df_before['Start_Date___Time'] = pd.to_datetime(df_before['Start_Date___Time'], dayfirst=False, errors='coerce')
    df_after['Start_Date___Time'] = pd.to_datetime(df_after['Start_Date___Time'], dayfirst=True, errors='coerce')

    # Combine back
    ev_df = pd.concat([df_before, df_after], ignore_index=True)

    # Drop invalid datetimes (NaT)
    ev_df = ev_df.dropna(subset=['Start_Date___Time'])

    # Keep only the date part (remove time)
    ev_df['Start_Date___Time'] = ev_df['Start_Date___Time'].dt.date

    print("✅ Date parsing completed successfully.")
    print(ev_df[['Start_Date___Time']].head())

else:
    print("❌ No rows matched the cutoff pattern '05/06/2023'. Please check the data manually.")

✅ Date parsing completed successfully.
  Start_Date___Time
0        2018-01-01
1        2018-01-02
2        2018-01-02
3        2018-01-03
4        2018-01-03

In [14]:
# Group by date and sum the energy column
ev_daily = ev_df.groupby('Start_Date___Time')['Energy__kWh_'].sum().reset_index()

# Rename columns for clarity
ev_daily.rename(columns={'Start_Date___Time': 'date', 'Energy__kWh_': 'energy'}, inplace=True)

# Preview the result
print(ev_daily.head())

         date  energy
0  2018-01-01   6.504
1  2018-01-02  17.527
2  2018-01-03  11.227
3  2018-01-04  49.748
4  2018-01-05   2.956

In [15]:
print(ev_daily.shape)

(2089, 2)

The dataset used in this study was obtained from the official Colorado government website, specifically covering electric vehicle (EV) charging sessions. The raw data contained over 148,000 rows and multiple features, including timestamps, energy consumption, station information, and IDs. The first step involved cleaning the data by dropping unnecessary columns such as ObjectID and ObjectId2, and identifying duplicate entries. A thorough examination revealed repeated rows, which were removed to avoid data leakage and bias. The Start_Date___Time column was then converted to a consistent datetime format (month/day/year) and simplified to retain only the date component, excluding the hour and minute. To prepare the data for time series analysis, daily aggregation was performed by grouping entries by date and summing the Energy__kWh_ values. This process produced a clean dataset with one energy consumption value per day, forming the basis for subsequent feature engineering and forecasting tasks.

In [16]:
#  Rename 'Energy__kWh_' to 'energy'
ev_daily.rename(columns={'Energy__kWh_': 'energy'}, inplace=True)
# 2️ Rename 'Energy__kWh_' to 'energy'
ev_daily.rename(columns={'Start_Date___Time': 'date'}, inplace=True)

In [17]:

# Ensure 'date' column is datetime
ev_daily['date'] = pd.to_datetime(ev_daily['date'])

# 1️⃣ First and Last Dates
first_date = ev_daily['date'].min()
last_date = ev_daily['date'].max()

print(f"📅 First date: {first_date.date()}")
print(f"📅 Last date:  {last_date.date()}")

# 2️⃣ Check for missing dates
# Create full expected date range
full_range = pd.date_range(start=first_date, end=last_date)

# Get actual dates in the dataset
actual_dates = pd.to_datetime(ev_daily['date'].unique())

# Identify any missing dates
missing_dates = set(full_range) - set(actual_dates)

# Result
if not missing_dates:
    print("✅ No missing dates. All dates are present.")
    print("👉 Result: True")
else:
    print(f"❌ Missing {len(missing_dates)} date(s).")
    print("👉 Result: False")
    print("Missing dates (examples):", sorted(list(missing_dates))[:5])

📅 First date: 2018-01-01
📅 Last date:  2023-12-11
❌ Missing 82 date(s).
👉 Result: False
Missing dates (examples): [Timestamp('2020-03-19 00:00:00'), Timestamp('2020-03-20 00:00:00'), Timestamp('2020-04-13 00:00:00'), Timestamp('2021-03-14 00:00:00'), Timestamp('2023-06-01 00:00:00')]

In [18]:
ev_daily.head()

        date  energy
0 2018-01-01   6.504
1 2018-01-02  17.527
2 2018-01-03  11.227
3 2018-01-04  49.748
4 2018-01-05   2.956

In [19]:
import pandas as pd

# Ensure 'date' column is datetime
ev_daily['date'] = pd.to_datetime(ev_daily['date'])

# Set 'date' as index
ev_daily = ev_daily.set_index('date')

# Create full date range from min to max
full_range = pd.date_range(start=ev_daily.index.min(), end=ev_daily.index.max(), freq='D')

# Identify missing dates
missing_dates = full_range.difference(ev_daily.index)

# Display the missing dates
print(f"Total missing dates: {len(missing_dates)}")
print("Missing dates:")
print(missing_dates)

Total missing dates: 82
Missing dates:
DatetimeIndex(['2020-03-19', '2020-03-20', '2020-04-13', '2021-03-14',
               '2023-06-01', '2023-09-01', '2023-09-02', '2023-09-03',
               '2023-09-04', '2023-09-12', '2023-09-13', '2023-09-14',
               '2023-09-15', '2023-09-16', '2023-09-17', '2023-09-18',
               '2023-09-19', '2023-09-20', '2023-09-21', '2023-09-22',
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04',
               '2023-10-05', '2023-10-12', '2023-10-13', '2023-10-14',
               '2023-10-15', '2023-10-16', '2023-10-17', '2023-10-18',
               '2023-10-19', '2023-10-20', '2023-10-21', '2023-10-22',
               '2023-10-23', '2023-10-24', '2023-10-25', '2023-10-26',
               '2023-10-27', '2023-10-28', '2023-10-29', '2023-10-30',
               '2023-10-31', '2023-11-01', '2023-11-02', '2023-11-03',
               '2023-11-04', '2023-11-05', '2023-11-12', '2023-11-13',
               '2023-11-14', '2023-11-15', '2023-11-16', '2023-11-17',
               '2023-11-18', '2023-11-19', '2023-11-20', '2023-11-21',
               '2023-11-22', '2023-11-23', '2023-11-24', '2023-11-25',
               '2023-11-26', '2023-11-27', '2023-11-28', '2023-11-29',
               '2023-11-30', '2023-12-01', '2023-12-02', '2023-12-03',
               '2023-12-04', '2023-12-05'],
              dtype='datetime64[ns]', freq=None)

In [20]:
# Reset index so 'date' becomes a column
ev_daily = ev_daily.reset_index()

# Ensure 'date' is in datetime format
ev_daily['date'] = pd.to_datetime(ev_daily['date'])

# Drop rows from 2023-08-01 to 2023-12-31
ev_daily = ev_daily[~((ev_daily['date'] >= '2023-08-01') & (ev_daily['date'] <= '2023-12-31'))]

# Optionally set date as index again
ev_daily = ev_daily.set_index('date')

# Preview
print(ev_daily.head())

            energy
date
2018-01-01   6.504
2018-01-02  17.527
2018-01-03  11.227
2018-01-04  49.748
2018-01-05   2.956

In [21]:
import pandas as pd

# If 'date' is already the index, no need to reset
if 'date' not in ev_daily.columns:
    date_index = ev_daily.index
else:
    ev_daily['date'] = pd.to_datetime(ev_daily['date'])  # ensure datetime
    ev_daily = ev_daily.set_index('date')
    date_index = ev_daily.index

# Create full date range from min to max
full_range = pd.date_range(start=date_index.min(), end=date_index.max(), freq='D')

# Identify missing dates
missing_dates = full_range.difference(date_index)

# Display results
print(f"📅 First date: {date_index.min().date()}")
print(f"📅 Last date:  {date_index.max().date()}")
print(f"❌ Total missing dates: {len(missing_dates)}")
print("Missing dates:")
print(missing_dates)

📅 First date: 2018-01-01
📅 Last date:  2023-07-31
❌ Total missing dates: 5
Missing dates:
DatetimeIndex(['2020-03-19', '2020-03-20', '2020-04-13', '2021-03-14',
               '2023-06-01'],
              dtype='datetime64[ns]', freq=None)

In [22]:
import pandas as pd

# Ensure 'ev_daily' is indexed by datetime
ev_daily = ev_daily.sort_index()
ev_daily = ev_daily.asfreq('D')  # Add missing dates with NaN

# Interpolate missing energy values linearly
ev_daily['energy'] = ev_daily['energy'].interpolate(method='linear')

# Check results
print(ev_daily.loc[ev_daily['energy'].isna()])  # Should be empty if all were filled

Empty DataFrame
Columns: [energy]
Index: []

In [23]:
# Save the interpolated DataFrame to a CSV file
ev_daily.to_csv("ev_daily_aggregated.csv", index=True)
print("✅ Saved as 'ev_daily_ev_daily_aggregated.csv'")

✅ Saved as 'ev_daily_ev_daily_aggregated.csv'